### ISSUE TITLE
درگاه پرداخت مشکل داره

### ISSUE THREAD

**Issue by toorajam** [when2meet-ir/webapp-issues#1]
![image](https://github.com/when2meet-ir/webapp/assets/4065518/f5b2b732-8577-4cf5-a8b4-75a15bf9832b)

**Comment by when2meet-ir** [comment]
سپاس بابت گزارش خطا
و پوزش بابت پاسخ دیرهنگام
در حال حاضر روش جایگزینی جهت حمایت مالی فراهم شده است
